const Categories = [
  {
    id: 1,
    title: "shirt1",
    category: "Men",
    price: 400,
    image: "../images/b1.jpg",
  },
  {
    id: 2,
    title: "shirt2",
    category: "Men",
    price: 600,
    image: "../images/b2.jpg",
  },
  {
    id: 3,
    title: "shirt3",
    category: "Men",
    price: 800,
    image: "../images/b3.jpg",
  },
  {
    id: 4,
    title: "tshirt",
    category: "Shirts",
    price: 300,
    image: "../images/t1.jpg",
  },
  {
    id: 5,
    title: "tshirt1",
    category: "Shirts",
    price: 200,
    image: "../images/t2.jpg",
  },
  {
    id: 6,
    title: "tshirt3",
    category: "Shirts",
    price: 250,
    image: "../images/o4.jpg",
  },
  {
    id: 7,
    title: "shoes",
    category: "Men",
    price: 550,
    image: "../images/j1.jpg",
  },
  {
    id: 8,
    title: "shoes2",
    category: "Men",
    price: 850,
    image: "../images/j2.jpg",
  },
  {
    id: 20,
    title: "shoes3",
    category: "Men",
    price: 550,
    image: "../images/j3.jpg",
  },
  {
    id: 9,
    title: "shoes4",
    category: "Men",
    price: 650,
    image: "../images/j4.jpg",
  },
  {
    id: 10,
    title: "sarri",
    category: "Women",
    price: 1150,
    image: "../images/s1.jpg",
  },
  {
    id: 11,
    title: "sarri",
    category: "Women",
    price: 1350,
    image: "../images/s2.jpg",
  },
  {
    id: 12,
    title: "suit",
    category: "Women",
    price: 650,
    image: "../images/o1.jpg",
  },
  {
    id: 13,
    title: "sport",
    category: "Women",
    price: 650,
    image: "../images/o2.jpg",
  },
  {
    id: 14,
    title: "Watch",
    category: "Men",
    price: 650,
    image: "../images/o3.jpg",
  },
];

export default Categories;
